variables:
  # DEV Environment
  ENVIRONMENT: IOT-IAC-DEV
  RESOURCE_GROUP: dmw2cxfrego01 
  LOCATION: westus2
  SERVICECONNECTION_RG: DEV-CORPTB-CICD-SPK0038145
  SUBSCRIPTIONID: "fe62782e-1d26-4c26-a97f-59d2827d521b"