variables:
  # DEV Environment
  ENVIRONMENT: IOT-IAC-DEV
  RESOURCE_GROUP: dmw2cxfrego02 
  LOCATION: westus2
  SERVICECONNECTION_RG: iot-infra
  SUBSCRIPTIONID: "d5f65e91-af0d-4148-b838-e9499596b56b"