# Pipeline that deploys the IOT infrastructure 

trigger:
- none

variables:
- template: ../configurations/configuration.variables.yml
- template: ../configurations/configuration-infra-DEV.variables.yml # DEV as default env

pool:
  vmImage: $(VM_VERSION)

stages:

####################
##  BUILD INFRA  ##
####################

# Lint the Bicep file.
- stage: buildinfra
  displayName: 'Build Environment'
  jobs: 
  - template: templates/run-code-lint.template.yml
    parameters:
      module: 'iot'

####################
##  DEPLOY INFRA  ##
####################

# Deploy DEV Environment
- stage: deployinfra_dev
  displayName: 'Deploy DEV Environment'
  dependsOn: buildinfra
  variables:
  - template: ../configurations/configuration-infra-DEV.variables.yml
  jobs:
  - template: templates/deploy-env-infra.template.yml
    parameters:
      environment: $(ENVIRONMENT)
      serviceConnection: $(SERVICECONNECTION_RG)
      resourceGroup: $(RESOURCE_GROUP)
      location: $(LOCATION)
      subscription: $(SUBSCRIPTIONID)
      module: 'iot'


# Deploy QA Environment
- stage: deployinfra_QA
  displayName: 'Deploy QA Environment'
  variables:
  - template: ../configurations/configuration-infra-QA.variables.yml
  jobs:
  - template: templates/deploy-env-infra.template.yml
    parameters:
      environment: IOT-IAC-QA
      serviceConnection: $(SERVICECONNECTION_RG)
      resourceGroup: $(RESOURCE_GROUP)
      location: $(LOCATION)
      subscription: $(SUBSCRIPTIONID)
      module: 'iot'

# Deploy PROD Environment
- stage: deployinfra_PROD
  displayName: 'Deploy PROD Environment'
  variables:
  - template: ../configurations/configuration-infra-PROD.variables.yml
  jobs:
  - template: templates/deploy-env-infra.template.yml
    parameters:
      environment: IOT-IAC-PROD
      serviceConnection: $(SERVICECONNECTION_RG)
      resourceGroup: $(RESOURCE_GROUP)
      location: $(LOCATION)
      subscription: $(SUBSCRIPTIONID)
      module: 'iot'            